### ISSUE TITLE
Doesn't handle dsa keys

### ISSUE THREAD

**Issue by chadkouse** [flplv/ssh-allow-friend#3]
script is hard coded to look for `ssh-rsa` at the beginning of the keyfile.  `ssh-dss` is also valid and should be supported.

See here:
https://github.com/chadkouse.keys

**Comment by flplv** [comment]
Using ssh-keygen to check keys integrity now, tested with your keys and it went fine.
Commit 3ceec28daca4c601fa167e2f52866de92bcd4b16
